# After changing this file, check it on:
# http://lint.travis-ci.org

language: python

sudo: false

python:
  - "3.4"

install:
    - pip install -U pip
    - pip install -U -r requirements.txt

script:
    - tar xvzf data.tar.gz
    - export PYTHONHASHSEED=0
    - python -m doctest lib/experiments.py
